/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.api;

import dev.gethook.ApiException;
import dev.gethook.model.APIKey;
import dev.gethook.model.APIKeyWithSecret;
import dev.gethook.model.CreateAPIKeyRequest;
import dev.gethook.model.ErrorResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApiKeysApi
 */
@Disabled
public class ApiKeysApiTest {

    private final ApiKeysApi api = new ApiKeysApi();

    /**
     * Create API key
     *
     * Creates a new API key for the authenticated account. The full key is only returned once.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createApiKeyTest() throws ApiException {
        CreateAPIKeyRequest createAPIKeyRequest = null;
        APIKeyWithSecret response = api.createApiKey(createAPIKeyRequest);
        // TODO: test validations
    }

    /**
     * Revoke API key
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteApiKeyTest() throws ApiException {
        String id = null;
        api.deleteApiKey(id);
        // TODO: test validations
    }

    /**
     * List API keys
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listApiKeysTest() throws ApiException {
        List<APIKey> response = api.listApiKeys();
        // TODO: test validations
    }

}
