/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.api;

import dev.gethook.ApiException;
import dev.gethook.model.AccountBootstrapData;
import dev.gethook.model.ErrorResponse;
import dev.gethook.model.LoginRequest;
import dev.gethook.model.RegisterRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthApi
 */
@Disabled
public class AuthApiTest {

    private final AuthApi api = new AuthApi();

    /**
     * Login with email and password
     *
     * Authenticates with email/password and returns a fresh API key on success.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void loginTest() throws ApiException {
        LoginRequest loginRequest = null;
        AccountBootstrapData response = api.login(loginRequest);
        // TODO: test validations
    }

    /**
     * Register with email and password
     *
     * Creates a new account with email/password credentials and returns a bootstrap API key.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void registerTest() throws ApiException {
        RegisterRequest registerRequest = null;
        AccountBootstrapData response = api.register(registerRequest);
        // TODO: test validations
    }

}
