/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.api;

import dev.gethook.ApiException;
import dev.gethook.model.BrandSettings;
import dev.gethook.model.ErrorResponse;
import dev.gethook.model.UpsertBrandSettingsRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BrandApi
 */
@Disabled
public class BrandApiTest {

    private final BrandApi api = new BrandApi();

    /**
     * Get brand settings
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBrandSettingsTest() throws ApiException {
        BrandSettings response = api.getBrandSettings();
        // TODO: test validations
    }

    /**
     * Upsert brand settings
     *
     * Creates or replaces white-label brand settings for the account.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void upsertBrandSettingsTest() throws ApiException {
        UpsertBrandSettingsRequest upsertBrandSettingsRequest = null;
        BrandSettings response = api.upsertBrandSettings(upsertBrandSettingsRequest);
        // TODO: test validations
    }

}
