/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.api;

import dev.gethook.ApiException;
import dev.gethook.model.CreateDestinationRequest;
import dev.gethook.model.Destination;
import dev.gethook.model.ErrorResponse;
import dev.gethook.model.UpdateDestinationRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DestinationsApi
 */
@Disabled
public class DestinationsApiTest {

    private final DestinationsApi api = new DestinationsApi();

    /**
     * Create destination
     *
     * Creates a new webhook delivery destination. The signing_secret is encrypted at rest and never returned.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createDestinationTest() throws ApiException {
        CreateDestinationRequest createDestinationRequest = null;
        Destination response = api.createDestination(createDestinationRequest);
        // TODO: test validations
    }

    /**
     * Get destination
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDestinationTest() throws ApiException {
        String id = null;
        Destination response = api.getDestination(id);
        // TODO: test validations
    }

    /**
     * List destinations
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listDestinationsTest() throws ApiException {
        List<Destination> response = api.listDestinations();
        // TODO: test validations
    }

    /**
     * Update destination
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateDestinationTest() throws ApiException {
        String id = null;
        UpdateDestinationRequest updateDestinationRequest = null;
        Destination response = api.updateDestination(id, updateDestinationRequest);
        // TODO: test validations
    }

}
