/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.api;

import dev.gethook.ApiException;
import dev.gethook.model.ErrorResponse;
import dev.gethook.model.EventDetailData;
import dev.gethook.model.EventListData;
import dev.gethook.model.ReplayEventData;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EventsApi
 */
@Disabled
public class EventsApiTest {

    private final EventsApi api = new EventsApi();

    /**
     * Get inbound event
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getEventTest() throws ApiException {
        String id = null;
        EventDetailData response = api.getEvent(id);
        // TODO: test validations
    }

    /**
     * List inbound events
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listEventsTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        EventListData response = api.listEvents(limit, offset);
        // TODO: test validations
    }

    /**
     * Replay inbound event
     *
     * Creates a new queued copy of the event for re-delivery.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void replayEventTest() throws ApiException {
        String id = null;
        ReplayEventData response = api.replayEvent(id);
        // TODO: test validations
    }

}
