/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.api;

import dev.gethook.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HealthApi
 */
@Disabled
public class HealthApiTest {

    private final HealthApi api = new HealthApi();

    /**
     * Liveness check
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void healthzTest() throws ApiException {
        Map<String, String> response = api.healthz();
        // TODO: test validations
    }

    /**
     * Readiness check
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void readyzTest() throws ApiException {
        Map<String, String> response = api.readyz();
        // TODO: test validations
    }

}
