/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.api;

import dev.gethook.ApiException;
import dev.gethook.model.ErrorResponse;
import dev.gethook.model.IngestAcceptedData;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IngestApi
 */
@Disabled
public class IngestApiTest {

    private final IngestApi api = new IngestApi();

    /**
     * Ingest webhook event
     *
     * Accepts an inbound webhook. The path token authenticates the source — no Bearer header required.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ingestTest() throws ApiException {
        String token = null;
        IngestAcceptedData response = api.ingest(token);
        // TODO: test validations
    }

}
