/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.api;

import dev.gethook.ApiException;
import dev.gethook.model.CreateSourceRequest;
import dev.gethook.model.ErrorResponse;
import dev.gethook.model.Source;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SourcesApi
 */
@Disabled
public class SourcesApiTest {

    private final SourcesApi api = new SourcesApi();

    /**
     * Create source
     *
     * Creates a new webhook source endpoint. Returns an ingest_url to share with the event sender.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createSourceTest() throws ApiException {
        CreateSourceRequest createSourceRequest = null;
        Source response = api.createSource(createSourceRequest);
        // TODO: test validations
    }

    /**
     * Get source
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSourceTest() throws ApiException {
        String id = null;
        Source response = api.getSource(id);
        // TODO: test validations
    }

    /**
     * List sources
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listSourcesTest() throws ApiException {
        List<Source> response = api.listSources();
        // TODO: test validations
    }

}
