/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AggregateTotals
 */
public class AggregateTotalsTest {
    private final AggregateTotals model = new AggregateTotals();

    /**
     * Model tests for AggregateTotals
     */
    @Test
    public void testAggregateTotals() {
        // TODO: test AggregateTotals
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

    /**
     * Test the property 'delivered'
     */
    @Test
    public void deliveredTest() {
        // TODO: test delivered
    }

    /**
     * Test the property 'failed'
     */
    @Test
    public void failedTest() {
        // TODO: test failed
    }

}
