/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateSourceRequest
 */
public class CreateSourceRequestTest {
    private final CreateSourceRequest model = new CreateSourceRequest();

    /**
     * Model tests for CreateSourceRequest
     */
    @Test
    public void testCreateSourceRequest() {
        // TODO: test CreateSourceRequest
    }

    /**
     * Test the property 'authMode'
     */
    @Test
    public void authModeTest() {
        // TODO: test authMode
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'verificationConfig'
     */
    @Test
    public void verificationConfigTest() {
        // TODO: test verificationConfig
    }

}
