/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PlatformStats
 */
public class PlatformStatsTest {
    private final PlatformStats model = new PlatformStats();

    /**
     * Model tests for PlatformStats
     */
    @Test
    public void testPlatformStats() {
        // TODO: test PlatformStats
    }

    /**
     * Test the property 'deliveryAttempts'
     */
    @Test
    public void deliveryAttemptsTest() {
        // TODO: test deliveryAttempts
    }

    /**
     * Test the property 'eventsDelivered'
     */
    @Test
    public void eventsDeliveredTest() {
        // TODO: test eventsDelivered
    }

    /**
     * Test the property 'eventsProcessed'
     */
    @Test
    public void eventsProcessedTest() {
        // TODO: test eventsProcessed
    }

    /**
     * Test the property 'successRatePct'
     */
    @Test
    public void successRatePctTest() {
        // TODO: test successRatePct
    }

}
