/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ReplayEventData
 */
public class ReplayEventDataTest {
    private final ReplayEventData model = new ReplayEventData();

    /**
     * Model tests for ReplayEventData
     */
    @Test
    public void testReplayEventData() {
        // TODO: test ReplayEventData
    }

    /**
     * Test the property 'originalEventId'
     */
    @Test
    public void originalEventIdTest() {
        // TODO: test originalEventId
    }

    /**
     * Test the property 'replayEventId'
     */
    @Test
    public void replayEventIdTest() {
        // TODO: test replayEventId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
