/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StatsDailyItem
 */
public class StatsDailyItemTest {
    private final StatsDailyItem model = new StatsDailyItem();

    /**
     * Model tests for StatsDailyItem
     */
    @Test
    public void testStatsDailyItem() {
        // TODO: test StatsDailyItem
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'delivered'
     */
    @Test
    public void deliveredTest() {
        // TODO: test delivered
    }

    /**
     * Test the property 'failed'
     */
    @Test
    public void failedTest() {
        // TODO: test failed
    }

    /**
     * Test the property 'inbound'
     */
    @Test
    public void inboundTest() {
        // TODO: test inbound
    }

    /**
     * Test the property 'outbound'
     */
    @Test
    public void outboundTest() {
        // TODO: test outbound
    }

}
