/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.gethook.model.StatsDailyItem;
import dev.gethook.model.StatsStatusItem;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StatsData
 */
public class StatsDataTest {
    private final StatsData model = new StatsData();

    /**
     * Model tests for StatsData
     */
    @Test
    public void testStatsData() {
        // TODO: test StatsData
    }

    /**
     * Test the property 'byStatus'
     */
    @Test
    public void byStatusTest() {
        // TODO: test byStatus
    }

    /**
     * Test the property 'daily'
     */
    @Test
    public void dailyTest() {
        // TODO: test daily
    }

}
