/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateDestinationRequest
 */
public class UpdateDestinationRequestTest {
    private final UpdateDestinationRequest model = new UpdateDestinationRequest();

    /**
     * Model tests for UpdateDestinationRequest
     */
    @Test
    public void testUpdateDestinationRequest() {
        // TODO: test UpdateDestinationRequest
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'authConfig'
     */
    @Test
    public void authConfigTest() {
        // TODO: test authConfig
    }

    /**
     * Test the property 'customHeaders'
     */
    @Test
    public void customHeadersTest() {
        // TODO: test customHeaders
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'timeoutSeconds'
     */
    @Test
    public void timeoutSecondsTest() {
        // TODO: test timeoutSeconds
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

}
