/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets AttemptOutcome
 */
@JsonAdapter(AttemptOutcome.Adapter.class)
public enum AttemptOutcome {
  
  OutcomePending("pending"),
  
  OutcomeSuccess("success"),
  
  OutcomeTimeout("timeout"),
  
  OutcomeNetworkError("network_error"),
  
  OutcomeHTTP4xx("http_4xx"),
  
  OutcomeHTTP5xx("http_5xx"),
  
  OutcomeCancelled("cancelled");

  private String value;

  AttemptOutcome(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AttemptOutcome fromValue(String value) {
    for (AttemptOutcome b : AttemptOutcome.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<AttemptOutcome> {
    @Override
    public void write(final JsonWriter jsonWriter, final AttemptOutcome enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AttemptOutcome read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AttemptOutcome.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    AttemptOutcome.fromValue(value);
  }
}

