/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dev.gethook.JSON;

/**
 * CreateDestinationRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-29T17:40:47.621211314Z[Etc/UTC]", comments = "Generator version: 7.20.0")
public class CreateDestinationRequest {
  public static final String SERIALIZED_NAME_AUTH_CONFIG = "auth_config";
  @SerializedName(SERIALIZED_NAME_AUTH_CONFIG)
  @javax.annotation.Nullable
  private Object authConfig;

  public static final String SERIALIZED_NAME_CUSTOM_HEADERS = "custom_headers";
  @SerializedName(SERIALIZED_NAME_CUSTOM_HEADERS)
  @javax.annotation.Nullable
  private Object customHeaders;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_SIGNING_SECRET = "signing_secret";
  @SerializedName(SERIALIZED_NAME_SIGNING_SECRET)
  @javax.annotation.Nullable
  private String signingSecret;

  public static final String SERIALIZED_NAME_TIMEOUT_SECONDS = "timeout_seconds";
  @SerializedName(SERIALIZED_NAME_TIMEOUT_SECONDS)
  @javax.annotation.Nullable
  private Integer timeoutSeconds;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  @javax.annotation.Nonnull
  private String url;

  public CreateDestinationRequest() {
  }

  public CreateDestinationRequest authConfig(@javax.annotation.Nullable Object authConfig) {
    this.authConfig = authConfig;
    return this;
  }

  /**
   * Get authConfig
   * @return authConfig
   */
  @javax.annotation.Nullable
  public Object getAuthConfig() {
    return authConfig;
  }

  public void setAuthConfig(@javax.annotation.Nullable Object authConfig) {
    this.authConfig = authConfig;
  }


  public CreateDestinationRequest customHeaders(@javax.annotation.Nullable Object customHeaders) {
    this.customHeaders = customHeaders;
    return this;
  }

  /**
   * Get customHeaders
   * @return customHeaders
   */
  @javax.annotation.Nullable
  public Object getCustomHeaders() {
    return customHeaders;
  }

  public void setCustomHeaders(@javax.annotation.Nullable Object customHeaders) {
    this.customHeaders = customHeaders;
  }


  public CreateDestinationRequest name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public CreateDestinationRequest signingSecret(@javax.annotation.Nullable String signingSecret) {
    this.signingSecret = signingSecret;
    return this;
  }

  /**
   * Get signingSecret
   * @return signingSecret
   */
  @javax.annotation.Nullable
  public String getSigningSecret() {
    return signingSecret;
  }

  public void setSigningSecret(@javax.annotation.Nullable String signingSecret) {
    this.signingSecret = signingSecret;
  }


  public CreateDestinationRequest timeoutSeconds(@javax.annotation.Nullable Integer timeoutSeconds) {
    this.timeoutSeconds = timeoutSeconds;
    return this;
  }

  /**
   * Get timeoutSeconds
   * @return timeoutSeconds
   */
  @javax.annotation.Nullable
  public Integer getTimeoutSeconds() {
    return timeoutSeconds;
  }

  public void setTimeoutSeconds(@javax.annotation.Nullable Integer timeoutSeconds) {
    this.timeoutSeconds = timeoutSeconds;
  }


  public CreateDestinationRequest url(@javax.annotation.Nonnull String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @javax.annotation.Nonnull
  public String getUrl() {
    return url;
  }

  public void setUrl(@javax.annotation.Nonnull String url) {
    this.url = url;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateDestinationRequest createDestinationRequest = (CreateDestinationRequest) o;
    return Objects.equals(this.authConfig, createDestinationRequest.authConfig) &&
        Objects.equals(this.customHeaders, createDestinationRequest.customHeaders) &&
        Objects.equals(this.name, createDestinationRequest.name) &&
        Objects.equals(this.signingSecret, createDestinationRequest.signingSecret) &&
        Objects.equals(this.timeoutSeconds, createDestinationRequest.timeoutSeconds) &&
        Objects.equals(this.url, createDestinationRequest.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authConfig, customHeaders, name, signingSecret, timeoutSeconds, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateDestinationRequest {\n");
    sb.append("    authConfig: ").append(toIndentedString(authConfig)).append("\n");
    sb.append("    customHeaders: ").append(toIndentedString(customHeaders)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    signingSecret: ").append(toIndentedString(signingSecret)).append("\n");
    sb.append("    timeoutSeconds: ").append(toIndentedString(timeoutSeconds)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("auth_config", "custom_headers", "name", "signing_secret", "timeout_seconds", "url"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("name", "url"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateDestinationRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateDestinationRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CreateDestinationRequest is not found in the empty JSON string", CreateDestinationRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateDestinationRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CreateDestinationRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateDestinationRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("signing_secret") != null && !jsonObj.get("signing_secret").isJsonNull()) && !jsonObj.get("signing_secret").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `signing_secret` to be a primitive type in the JSON string but got `%s`", jsonObj.get("signing_secret").toString()));
      }
      if (!jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateDestinationRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateDestinationRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateDestinationRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateDestinationRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateDestinationRequest>() {
           @Override
           public void write(JsonWriter out, CreateDestinationRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateDestinationRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateDestinationRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateDestinationRequest
   * @throws IOException if the JSON string is invalid with respect to CreateDestinationRequest
   */
  public static CreateDestinationRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateDestinationRequest.class);
  }

  /**
   * Convert an instance of CreateDestinationRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

