/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.gethook.model.AttemptOutcome;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dev.gethook.JSON;

/**
 * DeliveryAttempt
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-02T10:19:30.632986740Z[Etc/UTC]", comments = "Generator version: 7.20.0")
public class DeliveryAttempt {
  public static final String SERIALIZED_NAME_ATTEMPT_NUMBER = "attempt_number";
  @SerializedName(SERIALIZED_NAME_ATTEMPT_NUMBER)
  @javax.annotation.Nonnull
  private Integer attemptNumber;

  public static final String SERIALIZED_NAME_DESTINATION_ID = "destination_id";
  @SerializedName(SERIALIZED_NAME_DESTINATION_ID)
  @javax.annotation.Nonnull
  private String destinationId;

  public static final String SERIALIZED_NAME_ERROR_MESSAGE = "error_message";
  @SerializedName(SERIALIZED_NAME_ERROR_MESSAGE)
  @javax.annotation.Nullable
  private String errorMessage;

  public static final String SERIALIZED_NAME_EVENT_ID = "event_id";
  @SerializedName(SERIALIZED_NAME_EVENT_ID)
  @javax.annotation.Nonnull
  private String eventId;

  public static final String SERIALIZED_NAME_FINISHED_AT = "finished_at";
  @SerializedName(SERIALIZED_NAME_FINISHED_AT)
  @javax.annotation.Nullable
  private String finishedAt;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_LATENCY_MS = "latency_ms";
  @SerializedName(SERIALIZED_NAME_LATENCY_MS)
  @javax.annotation.Nullable
  private Integer latencyMs;

  public static final String SERIALIZED_NAME_OUTCOME = "outcome";
  @SerializedName(SERIALIZED_NAME_OUTCOME)
  @javax.annotation.Nonnull
  private AttemptOutcome outcome;

  public static final String SERIALIZED_NAME_RESPONSE_BODY = "response_body";
  @SerializedName(SERIALIZED_NAME_RESPONSE_BODY)
  @javax.annotation.Nullable
  private String responseBody;

  public static final String SERIALIZED_NAME_RESPONSE_STATUS = "response_status";
  @SerializedName(SERIALIZED_NAME_RESPONSE_STATUS)
  @javax.annotation.Nullable
  private Integer responseStatus;

  public static final String SERIALIZED_NAME_STARTED_AT = "started_at";
  @SerializedName(SERIALIZED_NAME_STARTED_AT)
  @javax.annotation.Nonnull
  private String startedAt;

  public DeliveryAttempt() {
  }

  public DeliveryAttempt attemptNumber(@javax.annotation.Nonnull Integer attemptNumber) {
    this.attemptNumber = attemptNumber;
    return this;
  }

  /**
   * Get attemptNumber
   * @return attemptNumber
   */
  @javax.annotation.Nonnull
  public Integer getAttemptNumber() {
    return attemptNumber;
  }

  public void setAttemptNumber(@javax.annotation.Nonnull Integer attemptNumber) {
    this.attemptNumber = attemptNumber;
  }


  public DeliveryAttempt destinationId(@javax.annotation.Nonnull String destinationId) {
    this.destinationId = destinationId;
    return this;
  }

  /**
   * Get destinationId
   * @return destinationId
   */
  @javax.annotation.Nonnull
  public String getDestinationId() {
    return destinationId;
  }

  public void setDestinationId(@javax.annotation.Nonnull String destinationId) {
    this.destinationId = destinationId;
  }


  public DeliveryAttempt errorMessage(@javax.annotation.Nullable String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

  /**
   * Get errorMessage
   * @return errorMessage
   */
  @javax.annotation.Nullable
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(@javax.annotation.Nullable String errorMessage) {
    this.errorMessage = errorMessage;
  }


  public DeliveryAttempt eventId(@javax.annotation.Nonnull String eventId) {
    this.eventId = eventId;
    return this;
  }

  /**
   * Get eventId
   * @return eventId
   */
  @javax.annotation.Nonnull
  public String getEventId() {
    return eventId;
  }

  public void setEventId(@javax.annotation.Nonnull String eventId) {
    this.eventId = eventId;
  }


  public DeliveryAttempt finishedAt(@javax.annotation.Nullable String finishedAt) {
    this.finishedAt = finishedAt;
    return this;
  }

  /**
   * Get finishedAt
   * @return finishedAt
   */
  @javax.annotation.Nullable
  public String getFinishedAt() {
    return finishedAt;
  }

  public void setFinishedAt(@javax.annotation.Nullable String finishedAt) {
    this.finishedAt = finishedAt;
  }


  public DeliveryAttempt id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public DeliveryAttempt latencyMs(@javax.annotation.Nullable Integer latencyMs) {
    this.latencyMs = latencyMs;
    return this;
  }

  /**
   * Get latencyMs
   * @return latencyMs
   */
  @javax.annotation.Nullable
  public Integer getLatencyMs() {
    return latencyMs;
  }

  public void setLatencyMs(@javax.annotation.Nullable Integer latencyMs) {
    this.latencyMs = latencyMs;
  }


  public DeliveryAttempt outcome(@javax.annotation.Nonnull AttemptOutcome outcome) {
    this.outcome = outcome;
    return this;
  }

  /**
   * Get outcome
   * @return outcome
   */
  @javax.annotation.Nonnull
  public AttemptOutcome getOutcome() {
    return outcome;
  }

  public void setOutcome(@javax.annotation.Nonnull AttemptOutcome outcome) {
    this.outcome = outcome;
  }


  public DeliveryAttempt responseBody(@javax.annotation.Nullable String responseBody) {
    this.responseBody = responseBody;
    return this;
  }

  /**
   * Get responseBody
   * @return responseBody
   */
  @javax.annotation.Nullable
  public String getResponseBody() {
    return responseBody;
  }

  public void setResponseBody(@javax.annotation.Nullable String responseBody) {
    this.responseBody = responseBody;
  }


  public DeliveryAttempt responseStatus(@javax.annotation.Nullable Integer responseStatus) {
    this.responseStatus = responseStatus;
    return this;
  }

  /**
   * Get responseStatus
   * @return responseStatus
   */
  @javax.annotation.Nullable
  public Integer getResponseStatus() {
    return responseStatus;
  }

  public void setResponseStatus(@javax.annotation.Nullable Integer responseStatus) {
    this.responseStatus = responseStatus;
  }


  public DeliveryAttempt startedAt(@javax.annotation.Nonnull String startedAt) {
    this.startedAt = startedAt;
    return this;
  }

  /**
   * Get startedAt
   * @return startedAt
   */
  @javax.annotation.Nonnull
  public String getStartedAt() {
    return startedAt;
  }

  public void setStartedAt(@javax.annotation.Nonnull String startedAt) {
    this.startedAt = startedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeliveryAttempt deliveryAttempt = (DeliveryAttempt) o;
    return Objects.equals(this.attemptNumber, deliveryAttempt.attemptNumber) &&
        Objects.equals(this.destinationId, deliveryAttempt.destinationId) &&
        Objects.equals(this.errorMessage, deliveryAttempt.errorMessage) &&
        Objects.equals(this.eventId, deliveryAttempt.eventId) &&
        Objects.equals(this.finishedAt, deliveryAttempt.finishedAt) &&
        Objects.equals(this.id, deliveryAttempt.id) &&
        Objects.equals(this.latencyMs, deliveryAttempt.latencyMs) &&
        Objects.equals(this.outcome, deliveryAttempt.outcome) &&
        Objects.equals(this.responseBody, deliveryAttempt.responseBody) &&
        Objects.equals(this.responseStatus, deliveryAttempt.responseStatus) &&
        Objects.equals(this.startedAt, deliveryAttempt.startedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attemptNumber, destinationId, errorMessage, eventId, finishedAt, id, latencyMs, outcome, responseBody, responseStatus, startedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeliveryAttempt {\n");
    sb.append("    attemptNumber: ").append(toIndentedString(attemptNumber)).append("\n");
    sb.append("    destinationId: ").append(toIndentedString(destinationId)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    finishedAt: ").append(toIndentedString(finishedAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    latencyMs: ").append(toIndentedString(latencyMs)).append("\n");
    sb.append("    outcome: ").append(toIndentedString(outcome)).append("\n");
    sb.append("    responseBody: ").append(toIndentedString(responseBody)).append("\n");
    sb.append("    responseStatus: ").append(toIndentedString(responseStatus)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("attempt_number", "destination_id", "error_message", "event_id", "finished_at", "id", "latency_ms", "outcome", "response_body", "response_status", "started_at"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("attempt_number", "destination_id", "event_id", "id", "outcome", "started_at"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DeliveryAttempt
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DeliveryAttempt.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in DeliveryAttempt is not found in the empty JSON string", DeliveryAttempt.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DeliveryAttempt.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `DeliveryAttempt` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DeliveryAttempt.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("destination_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `destination_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("destination_id").toString()));
      }
      if ((jsonObj.get("error_message") != null && !jsonObj.get("error_message").isJsonNull()) && !jsonObj.get("error_message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `error_message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("error_message").toString()));
      }
      if (!jsonObj.get("event_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `event_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("event_id").toString()));
      }
      if ((jsonObj.get("finished_at") != null && !jsonObj.get("finished_at").isJsonNull()) && !jsonObj.get("finished_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `finished_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("finished_at").toString()));
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      // validate the required field `outcome`
      AttemptOutcome.validateJsonElement(jsonObj.get("outcome"));
      if ((jsonObj.get("response_body") != null && !jsonObj.get("response_body").isJsonNull()) && !jsonObj.get("response_body").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `response_body` to be a primitive type in the JSON string but got `%s`", jsonObj.get("response_body").toString()));
      }
      if (!jsonObj.get("started_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `started_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("started_at").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DeliveryAttempt.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DeliveryAttempt' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DeliveryAttempt> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DeliveryAttempt.class));

       return (TypeAdapter<T>) new TypeAdapter<DeliveryAttempt>() {
           @Override
           public void write(JsonWriter out, DeliveryAttempt value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DeliveryAttempt read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DeliveryAttempt given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DeliveryAttempt
   * @throws IOException if the JSON string is invalid with respect to DeliveryAttempt
   */
  public static DeliveryAttempt fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DeliveryAttempt.class);
  }

  /**
   * Convert an instance of DeliveryAttempt to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

