/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dev.gethook.JSON;

/**
 * DestinationPreset
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T22:22:43.877650515Z[Etc/UTC]", comments = "Generator version: 7.20.0")
public class DestinationPreset {
  public static final String SERIALIZED_NAME_AUTH_HEADER = "auth_header";
  @SerializedName(SERIALIZED_NAME_AUTH_HEADER)
  @javax.annotation.Nullable
  private String authHeader;

  public static final String SERIALIZED_NAME_AUTH_LABEL = "auth_label";
  @SerializedName(SERIALIZED_NAME_AUTH_LABEL)
  @javax.annotation.Nullable
  private String authLabel;

  public static final String SERIALIZED_NAME_AUTH_TYPE = "auth_type";
  @SerializedName(SERIALIZED_NAME_AUTH_TYPE)
  @javax.annotation.Nullable
  private String authType;

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  @javax.annotation.Nullable
  private String category;

  public static final String SERIALIZED_NAME_COLOR = "color";
  @SerializedName(SERIALIZED_NAME_COLOR)
  @javax.annotation.Nullable
  private String color;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_DOCS_URL = "docs_url";
  @SerializedName(SERIALIZED_NAME_DOCS_URL)
  @javax.annotation.Nullable
  private String docsUrl;

  public static final String SERIALIZED_NAME_EXTRA_HEADERS = "extra_headers";
  @SerializedName(SERIALIZED_NAME_EXTRA_HEADERS)
  @javax.annotation.Nullable
  private Map<String, String> extraHeaders = new HashMap<>();

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_URL_HINT = "url_hint";
  @SerializedName(SERIALIZED_NAME_URL_HINT)
  @javax.annotation.Nullable
  private String urlHint;

  public DestinationPreset() {
  }

  public DestinationPreset authHeader(@javax.annotation.Nullable String authHeader) {
    this.authHeader = authHeader;
    return this;
  }

  /**
   * for api_key type
   * @return authHeader
   */
  @javax.annotation.Nullable
  public String getAuthHeader() {
    return authHeader;
  }

  public void setAuthHeader(@javax.annotation.Nullable String authHeader) {
    this.authHeader = authHeader;
  }


  public DestinationPreset authLabel(@javax.annotation.Nullable String authLabel) {
    this.authLabel = authLabel;
    return this;
  }

  /**
   * e.g. \&quot;Bot Token\&quot;, \&quot;API Key\&quot;
   * @return authLabel
   */
  @javax.annotation.Nullable
  public String getAuthLabel() {
    return authLabel;
  }

  public void setAuthLabel(@javax.annotation.Nullable String authLabel) {
    this.authLabel = authLabel;
  }


  public DestinationPreset authType(@javax.annotation.Nullable String authType) {
    this.authType = authType;
    return this;
  }

  /**
   * \&quot;none\&quot;, \&quot;bearer\&quot;, \&quot;api_key\&quot;
   * @return authType
   */
  @javax.annotation.Nullable
  public String getAuthType() {
    return authType;
  }

  public void setAuthType(@javax.annotation.Nullable String authType) {
    this.authType = authType;
  }


  public DestinationPreset category(@javax.annotation.Nullable String category) {
    this.category = category;
    return this;
  }

  /**
   * Get category
   * @return category
   */
  @javax.annotation.Nullable
  public String getCategory() {
    return category;
  }

  public void setCategory(@javax.annotation.Nullable String category) {
    this.category = category;
  }


  public DestinationPreset color(@javax.annotation.Nullable String color) {
    this.color = color;
    return this;
  }

  /**
   * Get color
   * @return color
   */
  @javax.annotation.Nullable
  public String getColor() {
    return color;
  }

  public void setColor(@javax.annotation.Nullable String color) {
    this.color = color;
  }


  public DestinationPreset description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public DestinationPreset docsUrl(@javax.annotation.Nullable String docsUrl) {
    this.docsUrl = docsUrl;
    return this;
  }

  /**
   * Get docsUrl
   * @return docsUrl
   */
  @javax.annotation.Nullable
  public String getDocsUrl() {
    return docsUrl;
  }

  public void setDocsUrl(@javax.annotation.Nullable String docsUrl) {
    this.docsUrl = docsUrl;
  }


  public DestinationPreset extraHeaders(@javax.annotation.Nullable Map<String, String> extraHeaders) {
    this.extraHeaders = extraHeaders;
    return this;
  }

  public DestinationPreset putExtraHeadersItem(String key, String extraHeadersItem) {
    if (this.extraHeaders == null) {
      this.extraHeaders = new HashMap<>();
    }
    this.extraHeaders.put(key, extraHeadersItem);
    return this;
  }

  /**
   * Get extraHeaders
   * @return extraHeaders
   */
  @javax.annotation.Nullable
  public Map<String, String> getExtraHeaders() {
    return extraHeaders;
  }

  public void setExtraHeaders(@javax.annotation.Nullable Map<String, String> extraHeaders) {
    this.extraHeaders = extraHeaders;
  }


  public DestinationPreset id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public DestinationPreset name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public DestinationPreset urlHint(@javax.annotation.Nullable String urlHint) {
    this.urlHint = urlHint;
    return this;
  }

  /**
   * Get urlHint
   * @return urlHint
   */
  @javax.annotation.Nullable
  public String getUrlHint() {
    return urlHint;
  }

  public void setUrlHint(@javax.annotation.Nullable String urlHint) {
    this.urlHint = urlHint;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DestinationPreset destinationPreset = (DestinationPreset) o;
    return Objects.equals(this.authHeader, destinationPreset.authHeader) &&
        Objects.equals(this.authLabel, destinationPreset.authLabel) &&
        Objects.equals(this.authType, destinationPreset.authType) &&
        Objects.equals(this.category, destinationPreset.category) &&
        Objects.equals(this.color, destinationPreset.color) &&
        Objects.equals(this.description, destinationPreset.description) &&
        Objects.equals(this.docsUrl, destinationPreset.docsUrl) &&
        Objects.equals(this.extraHeaders, destinationPreset.extraHeaders) &&
        Objects.equals(this.id, destinationPreset.id) &&
        Objects.equals(this.name, destinationPreset.name) &&
        Objects.equals(this.urlHint, destinationPreset.urlHint);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authHeader, authLabel, authType, category, color, description, docsUrl, extraHeaders, id, name, urlHint);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DestinationPreset {\n");
    sb.append("    authHeader: ").append(toIndentedString(authHeader)).append("\n");
    sb.append("    authLabel: ").append(toIndentedString(authLabel)).append("\n");
    sb.append("    authType: ").append(toIndentedString(authType)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    docsUrl: ").append(toIndentedString(docsUrl)).append("\n");
    sb.append("    extraHeaders: ").append(toIndentedString(extraHeaders)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    urlHint: ").append(toIndentedString(urlHint)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("auth_header", "auth_label", "auth_type", "category", "color", "description", "docs_url", "extra_headers", "id", "name", "url_hint"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DestinationPreset
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DestinationPreset.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in DestinationPreset is not found in the empty JSON string", DestinationPreset.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DestinationPreset.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `DestinationPreset` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("auth_header") != null && !jsonObj.get("auth_header").isJsonNull()) && !jsonObj.get("auth_header").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `auth_header` to be a primitive type in the JSON string but got `%s`", jsonObj.get("auth_header").toString()));
      }
      if ((jsonObj.get("auth_label") != null && !jsonObj.get("auth_label").isJsonNull()) && !jsonObj.get("auth_label").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `auth_label` to be a primitive type in the JSON string but got `%s`", jsonObj.get("auth_label").toString()));
      }
      if ((jsonObj.get("auth_type") != null && !jsonObj.get("auth_type").isJsonNull()) && !jsonObj.get("auth_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `auth_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("auth_type").toString()));
      }
      if ((jsonObj.get("category") != null && !jsonObj.get("category").isJsonNull()) && !jsonObj.get("category").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `category` to be a primitive type in the JSON string but got `%s`", jsonObj.get("category").toString()));
      }
      if ((jsonObj.get("color") != null && !jsonObj.get("color").isJsonNull()) && !jsonObj.get("color").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `color` to be a primitive type in the JSON string but got `%s`", jsonObj.get("color").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("docs_url") != null && !jsonObj.get("docs_url").isJsonNull()) && !jsonObj.get("docs_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `docs_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("docs_url").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("url_hint") != null && !jsonObj.get("url_hint").isJsonNull()) && !jsonObj.get("url_hint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `url_hint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url_hint").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DestinationPreset.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DestinationPreset' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DestinationPreset> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DestinationPreset.class));

       return (TypeAdapter<T>) new TypeAdapter<DestinationPreset>() {
           @Override
           public void write(JsonWriter out, DestinationPreset value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DestinationPreset read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DestinationPreset given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DestinationPreset
   * @throws IOException if the JSON string is invalid with respect to DestinationPreset
   */
  public static DestinationPreset fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DestinationPreset.class);
  }

  /**
   * Convert an instance of DestinationPreset to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

