/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.gethook.model.Direction;
import dev.gethook.model.EventStatus;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dev.gethook.JSON;

/**
 * Event
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-03T11:52:49.526761323Z[Etc/UTC]", comments = "Generator version: 7.20.0")
public class Event {
  public static final String SERIALIZED_NAME_ACCOUNT_ID = "account_id";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
  @javax.annotation.Nonnull
  private String accountId;

  public static final String SERIALIZED_NAME_ATTEMPTS_COUNT = "attempts_count";
  @SerializedName(SERIALIZED_NAME_ATTEMPTS_COUNT)
  @javax.annotation.Nonnull
  private Integer attemptsCount;

  public static final String SERIALIZED_NAME_BODY = "body";
  @SerializedName(SERIALIZED_NAME_BODY)
  @javax.annotation.Nonnull
  private String body;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private String createdAt;

  public static final String SERIALIZED_NAME_CREATED_BY = "created_by";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  @javax.annotation.Nullable
  private String createdBy;

  public static final String SERIALIZED_NAME_DIRECTION = "direction";
  @SerializedName(SERIALIZED_NAME_DIRECTION)
  @javax.annotation.Nonnull
  private Direction direction;

  public static final String SERIALIZED_NAME_EVENT_TYPE = "event_type";
  @SerializedName(SERIALIZED_NAME_EVENT_TYPE)
  @javax.annotation.Nullable
  private String eventType;

  public static final String SERIALIZED_NAME_EXTERNAL_EVENT_ID = "external_event_id";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_EVENT_ID)
  @javax.annotation.Nullable
  private String externalEventId;

  public static final String SERIALIZED_NAME_FINAL_STATE = "final_state";
  @SerializedName(SERIALIZED_NAME_FINAL_STATE)
  @javax.annotation.Nullable
  private String finalState;

  public static final String SERIALIZED_NAME_HEADERS = "headers";
  @SerializedName(SERIALIZED_NAME_HEADERS)
  @javax.annotation.Nonnull
  private Map<String, Object> headers = new HashMap<>();

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_NEXT_ATTEMPT_AT = "next_attempt_at";
  @SerializedName(SERIALIZED_NAME_NEXT_ATTEMPT_AT)
  @javax.annotation.Nullable
  private String nextAttemptAt;

  public static final String SERIALIZED_NAME_PAYLOAD_HASH = "payload_hash";
  @SerializedName(SERIALIZED_NAME_PAYLOAD_HASH)
  @javax.annotation.Nullable
  private String payloadHash;

  public static final String SERIALIZED_NAME_RECEIVED_AT = "received_at";
  @SerializedName(SERIALIZED_NAME_RECEIVED_AT)
  @javax.annotation.Nonnull
  private String receivedAt;

  public static final String SERIALIZED_NAME_SOURCE_ID = "source_id";
  @SerializedName(SERIALIZED_NAME_SOURCE_ID)
  @javax.annotation.Nullable
  private String sourceId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private EventStatus status;

  public Event() {
  }

  public Event accountId(@javax.annotation.Nonnull String accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Get accountId
   * @return accountId
   */
  @javax.annotation.Nonnull
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(@javax.annotation.Nonnull String accountId) {
    this.accountId = accountId;
  }


  public Event attemptsCount(@javax.annotation.Nonnull Integer attemptsCount) {
    this.attemptsCount = attemptsCount;
    return this;
  }

  /**
   * Get attemptsCount
   * @return attemptsCount
   */
  @javax.annotation.Nonnull
  public Integer getAttemptsCount() {
    return attemptsCount;
  }

  public void setAttemptsCount(@javax.annotation.Nonnull Integer attemptsCount) {
    this.attemptsCount = attemptsCount;
  }


  public Event body(@javax.annotation.Nonnull String body) {
    this.body = body;
    return this;
  }

  /**
   * Get body
   * @return body
   */
  @javax.annotation.Nonnull
  public String getBody() {
    return body;
  }

  public void setBody(@javax.annotation.Nonnull String body) {
    this.body = body;
  }


  public Event createdAt(@javax.annotation.Nonnull String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull String createdAt) {
    this.createdAt = createdAt;
  }


  public Event createdBy(@javax.annotation.Nullable String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

  /**
   * Get createdBy
   * @return createdBy
   */
  @javax.annotation.Nullable
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(@javax.annotation.Nullable String createdBy) {
    this.createdBy = createdBy;
  }


  public Event direction(@javax.annotation.Nonnull Direction direction) {
    this.direction = direction;
    return this;
  }

  /**
   * Get direction
   * @return direction
   */
  @javax.annotation.Nonnull
  public Direction getDirection() {
    return direction;
  }

  public void setDirection(@javax.annotation.Nonnull Direction direction) {
    this.direction = direction;
  }


  public Event eventType(@javax.annotation.Nullable String eventType) {
    this.eventType = eventType;
    return this;
  }

  /**
   * Get eventType
   * @return eventType
   */
  @javax.annotation.Nullable
  public String getEventType() {
    return eventType;
  }

  public void setEventType(@javax.annotation.Nullable String eventType) {
    this.eventType = eventType;
  }


  public Event externalEventId(@javax.annotation.Nullable String externalEventId) {
    this.externalEventId = externalEventId;
    return this;
  }

  /**
   * Get externalEventId
   * @return externalEventId
   */
  @javax.annotation.Nullable
  public String getExternalEventId() {
    return externalEventId;
  }

  public void setExternalEventId(@javax.annotation.Nullable String externalEventId) {
    this.externalEventId = externalEventId;
  }


  public Event finalState(@javax.annotation.Nullable String finalState) {
    this.finalState = finalState;
    return this;
  }

  /**
   * Get finalState
   * @return finalState
   */
  @javax.annotation.Nullable
  public String getFinalState() {
    return finalState;
  }

  public void setFinalState(@javax.annotation.Nullable String finalState) {
    this.finalState = finalState;
  }


  public Event headers(@javax.annotation.Nonnull Map<String, Object> headers) {
    this.headers = headers;
    return this;
  }

  public Event putHeadersItem(String key, Object headersItem) {
    if (this.headers == null) {
      this.headers = new HashMap<>();
    }
    this.headers.put(key, headersItem);
    return this;
  }

  /**
   * Get headers
   * @return headers
   */
  @javax.annotation.Nonnull
  public Map<String, Object> getHeaders() {
    return headers;
  }

  public void setHeaders(@javax.annotation.Nonnull Map<String, Object> headers) {
    this.headers = headers;
  }


  public Event id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public Event nextAttemptAt(@javax.annotation.Nullable String nextAttemptAt) {
    this.nextAttemptAt = nextAttemptAt;
    return this;
  }

  /**
   * Get nextAttemptAt
   * @return nextAttemptAt
   */
  @javax.annotation.Nullable
  public String getNextAttemptAt() {
    return nextAttemptAt;
  }

  public void setNextAttemptAt(@javax.annotation.Nullable String nextAttemptAt) {
    this.nextAttemptAt = nextAttemptAt;
  }


  public Event payloadHash(@javax.annotation.Nullable String payloadHash) {
    this.payloadHash = payloadHash;
    return this;
  }

  /**
   * Get payloadHash
   * @return payloadHash
   */
  @javax.annotation.Nullable
  public String getPayloadHash() {
    return payloadHash;
  }

  public void setPayloadHash(@javax.annotation.Nullable String payloadHash) {
    this.payloadHash = payloadHash;
  }


  public Event receivedAt(@javax.annotation.Nonnull String receivedAt) {
    this.receivedAt = receivedAt;
    return this;
  }

  /**
   * Get receivedAt
   * @return receivedAt
   */
  @javax.annotation.Nonnull
  public String getReceivedAt() {
    return receivedAt;
  }

  public void setReceivedAt(@javax.annotation.Nonnull String receivedAt) {
    this.receivedAt = receivedAt;
  }


  public Event sourceId(@javax.annotation.Nullable String sourceId) {
    this.sourceId = sourceId;
    return this;
  }

  /**
   * Get sourceId
   * @return sourceId
   */
  @javax.annotation.Nullable
  public String getSourceId() {
    return sourceId;
  }

  public void setSourceId(@javax.annotation.Nullable String sourceId) {
    this.sourceId = sourceId;
  }


  public Event status(@javax.annotation.Nonnull EventStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public EventStatus getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull EventStatus status) {
    this.status = status;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Event event = (Event) o;
    return Objects.equals(this.accountId, event.accountId) &&
        Objects.equals(this.attemptsCount, event.attemptsCount) &&
        Objects.equals(this.body, event.body) &&
        Objects.equals(this.createdAt, event.createdAt) &&
        Objects.equals(this.createdBy, event.createdBy) &&
        Objects.equals(this.direction, event.direction) &&
        Objects.equals(this.eventType, event.eventType) &&
        Objects.equals(this.externalEventId, event.externalEventId) &&
        Objects.equals(this.finalState, event.finalState) &&
        Objects.equals(this.headers, event.headers) &&
        Objects.equals(this.id, event.id) &&
        Objects.equals(this.nextAttemptAt, event.nextAttemptAt) &&
        Objects.equals(this.payloadHash, event.payloadHash) &&
        Objects.equals(this.receivedAt, event.receivedAt) &&
        Objects.equals(this.sourceId, event.sourceId) &&
        Objects.equals(this.status, event.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, attemptsCount, body, createdAt, createdBy, direction, eventType, externalEventId, finalState, headers, id, nextAttemptAt, payloadHash, receivedAt, sourceId, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Event {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    attemptsCount: ").append(toIndentedString(attemptsCount)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    externalEventId: ").append(toIndentedString(externalEventId)).append("\n");
    sb.append("    finalState: ").append(toIndentedString(finalState)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nextAttemptAt: ").append(toIndentedString(nextAttemptAt)).append("\n");
    sb.append("    payloadHash: ").append(toIndentedString(payloadHash)).append("\n");
    sb.append("    receivedAt: ").append(toIndentedString(receivedAt)).append("\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("account_id", "attempts_count", "body", "created_at", "created_by", "direction", "event_type", "external_event_id", "final_state", "headers", "id", "next_attempt_at", "payload_hash", "received_at", "source_id", "status"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("account_id", "attempts_count", "body", "created_at", "direction", "headers", "id", "received_at", "status"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Event
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Event.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Event is not found in the empty JSON string", Event.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Event.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Event` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Event.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("account_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `account_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("account_id").toString()));
      }
      if (!jsonObj.get("body").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `body` to be a primitive type in the JSON string but got `%s`", jsonObj.get("body").toString()));
      }
      if (!jsonObj.get("created_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `created_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("created_at").toString()));
      }
      if ((jsonObj.get("created_by") != null && !jsonObj.get("created_by").isJsonNull()) && !jsonObj.get("created_by").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `created_by` to be a primitive type in the JSON string but got `%s`", jsonObj.get("created_by").toString()));
      }
      // validate the required field `direction`
      Direction.validateJsonElement(jsonObj.get("direction"));
      if ((jsonObj.get("event_type") != null && !jsonObj.get("event_type").isJsonNull()) && !jsonObj.get("event_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `event_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("event_type").toString()));
      }
      if ((jsonObj.get("external_event_id") != null && !jsonObj.get("external_event_id").isJsonNull()) && !jsonObj.get("external_event_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `external_event_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("external_event_id").toString()));
      }
      if ((jsonObj.get("final_state") != null && !jsonObj.get("final_state").isJsonNull()) && !jsonObj.get("final_state").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `final_state` to be a primitive type in the JSON string but got `%s`", jsonObj.get("final_state").toString()));
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("next_attempt_at") != null && !jsonObj.get("next_attempt_at").isJsonNull()) && !jsonObj.get("next_attempt_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `next_attempt_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("next_attempt_at").toString()));
      }
      if ((jsonObj.get("payload_hash") != null && !jsonObj.get("payload_hash").isJsonNull()) && !jsonObj.get("payload_hash").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `payload_hash` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payload_hash").toString()));
      }
      if (!jsonObj.get("received_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `received_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("received_at").toString()));
      }
      if ((jsonObj.get("source_id") != null && !jsonObj.get("source_id").isJsonNull()) && !jsonObj.get("source_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `source_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("source_id").toString()));
      }
      // validate the required field `status`
      EventStatus.validateJsonElement(jsonObj.get("status"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Event.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Event' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Event> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Event.class));

       return (TypeAdapter<T>) new TypeAdapter<Event>() {
           @Override
           public void write(JsonWriter out, Event value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Event read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Event given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Event
   * @throws IOException if the JSON string is invalid with respect to Event
   */
  public static Event fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Event.class);
  }

  /**
   * Convert an instance of Event to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

