/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets EventStatus
 */
@JsonAdapter(EventStatus.Adapter.class)
public enum EventStatus {
  
  StatusReceived("received"),
  
  StatusAccepted("accepted"),
  
  StatusQueued("queued"),
  
  StatusDelivering("delivering"),
  
  StatusDelivered("delivered"),
  
  StatusRetryScheduled("retry_scheduled"),
  
  StatusDeadLetter("dead_letter"),
  
  StatusReplayed("replayed");

  private String value;

  EventStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EventStatus fromValue(String value) {
    for (EventStatus b : EventStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<EventStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final EventStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EventStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EventStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    EventStatus.fromValue(value);
  }
}

