/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dev.gethook.JSON;

/**
 * PlatformStats
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-25T21:12:20.197395346Z[Etc/UTC]", comments = "Generator version: 7.20.0")
public class PlatformStats {
  public static final String SERIALIZED_NAME_DELIVERY_ATTEMPTS = "delivery_attempts";
  @SerializedName(SERIALIZED_NAME_DELIVERY_ATTEMPTS)
  @javax.annotation.Nullable
  private Integer deliveryAttempts;

  public static final String SERIALIZED_NAME_EVENTS_DELIVERED = "events_delivered";
  @SerializedName(SERIALIZED_NAME_EVENTS_DELIVERED)
  @javax.annotation.Nullable
  private Integer eventsDelivered;

  public static final String SERIALIZED_NAME_EVENTS_PROCESSED = "events_processed";
  @SerializedName(SERIALIZED_NAME_EVENTS_PROCESSED)
  @javax.annotation.Nullable
  private Integer eventsProcessed;

  public static final String SERIALIZED_NAME_SUCCESS_RATE_PCT = "success_rate_pct";
  @SerializedName(SERIALIZED_NAME_SUCCESS_RATE_PCT)
  @javax.annotation.Nullable
  private BigDecimal successRatePct;

  public PlatformStats() {
  }

  public PlatformStats deliveryAttempts(@javax.annotation.Nullable Integer deliveryAttempts) {
    this.deliveryAttempts = deliveryAttempts;
    return this;
  }

  /**
   * Get deliveryAttempts
   * @return deliveryAttempts
   */
  @javax.annotation.Nullable
  public Integer getDeliveryAttempts() {
    return deliveryAttempts;
  }

  public void setDeliveryAttempts(@javax.annotation.Nullable Integer deliveryAttempts) {
    this.deliveryAttempts = deliveryAttempts;
  }


  public PlatformStats eventsDelivered(@javax.annotation.Nullable Integer eventsDelivered) {
    this.eventsDelivered = eventsDelivered;
    return this;
  }

  /**
   * Get eventsDelivered
   * @return eventsDelivered
   */
  @javax.annotation.Nullable
  public Integer getEventsDelivered() {
    return eventsDelivered;
  }

  public void setEventsDelivered(@javax.annotation.Nullable Integer eventsDelivered) {
    this.eventsDelivered = eventsDelivered;
  }


  public PlatformStats eventsProcessed(@javax.annotation.Nullable Integer eventsProcessed) {
    this.eventsProcessed = eventsProcessed;
    return this;
  }

  /**
   * Get eventsProcessed
   * @return eventsProcessed
   */
  @javax.annotation.Nullable
  public Integer getEventsProcessed() {
    return eventsProcessed;
  }

  public void setEventsProcessed(@javax.annotation.Nullable Integer eventsProcessed) {
    this.eventsProcessed = eventsProcessed;
  }


  public PlatformStats successRatePct(@javax.annotation.Nullable BigDecimal successRatePct) {
    this.successRatePct = successRatePct;
    return this;
  }

  /**
   * Get successRatePct
   * @return successRatePct
   */
  @javax.annotation.Nullable
  public BigDecimal getSuccessRatePct() {
    return successRatePct;
  }

  public void setSuccessRatePct(@javax.annotation.Nullable BigDecimal successRatePct) {
    this.successRatePct = successRatePct;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlatformStats platformStats = (PlatformStats) o;
    return Objects.equals(this.deliveryAttempts, platformStats.deliveryAttempts) &&
        Objects.equals(this.eventsDelivered, platformStats.eventsDelivered) &&
        Objects.equals(this.eventsProcessed, platformStats.eventsProcessed) &&
        Objects.equals(this.successRatePct, platformStats.successRatePct);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveryAttempts, eventsDelivered, eventsProcessed, successRatePct);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlatformStats {\n");
    sb.append("    deliveryAttempts: ").append(toIndentedString(deliveryAttempts)).append("\n");
    sb.append("    eventsDelivered: ").append(toIndentedString(eventsDelivered)).append("\n");
    sb.append("    eventsProcessed: ").append(toIndentedString(eventsProcessed)).append("\n");
    sb.append("    successRatePct: ").append(toIndentedString(successRatePct)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("delivery_attempts", "events_delivered", "events_processed", "success_rate_pct"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PlatformStats
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PlatformStats.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in PlatformStats is not found in the empty JSON string", PlatformStats.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PlatformStats.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `PlatformStats` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PlatformStats.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PlatformStats' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PlatformStats> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PlatformStats.class));

       return (TypeAdapter<T>) new TypeAdapter<PlatformStats>() {
           @Override
           public void write(JsonWriter out, PlatformStats value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PlatformStats read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PlatformStats given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PlatformStats
   * @throws IOException if the JSON string is invalid with respect to PlatformStats
   */
  public static PlatformStats fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PlatformStats.class);
  }

  /**
   * Convert an instance of PlatformStats to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

