/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dev.gethook.JSON;

/**
 * ReplayEventData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-29T21:07:32.711968626Z[Etc/UTC]", comments = "Generator version: 7.20.0")
public class ReplayEventData {
  public static final String SERIALIZED_NAME_ORIGINAL_EVENT_ID = "original_event_id";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_EVENT_ID)
  @javax.annotation.Nonnull
  private String originalEventId;

  public static final String SERIALIZED_NAME_REPLAY_EVENT_ID = "replay_event_id";
  @SerializedName(SERIALIZED_NAME_REPLAY_EVENT_ID)
  @javax.annotation.Nonnull
  private String replayEventId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private String status;

  public ReplayEventData() {
  }

  public ReplayEventData originalEventId(@javax.annotation.Nonnull String originalEventId) {
    this.originalEventId = originalEventId;
    return this;
  }

  /**
   * Get originalEventId
   * @return originalEventId
   */
  @javax.annotation.Nonnull
  public String getOriginalEventId() {
    return originalEventId;
  }

  public void setOriginalEventId(@javax.annotation.Nonnull String originalEventId) {
    this.originalEventId = originalEventId;
  }


  public ReplayEventData replayEventId(@javax.annotation.Nonnull String replayEventId) {
    this.replayEventId = replayEventId;
    return this;
  }

  /**
   * Get replayEventId
   * @return replayEventId
   */
  @javax.annotation.Nonnull
  public String getReplayEventId() {
    return replayEventId;
  }

  public void setReplayEventId(@javax.annotation.Nonnull String replayEventId) {
    this.replayEventId = replayEventId;
  }


  public ReplayEventData status(@javax.annotation.Nonnull String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull String status) {
    this.status = status;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReplayEventData replayEventData = (ReplayEventData) o;
    return Objects.equals(this.originalEventId, replayEventData.originalEventId) &&
        Objects.equals(this.replayEventId, replayEventData.replayEventId) &&
        Objects.equals(this.status, replayEventData.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(originalEventId, replayEventId, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReplayEventData {\n");
    sb.append("    originalEventId: ").append(toIndentedString(originalEventId)).append("\n");
    sb.append("    replayEventId: ").append(toIndentedString(replayEventId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("original_event_id", "replay_event_id", "status"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("original_event_id", "replay_event_id", "status"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ReplayEventData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ReplayEventData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ReplayEventData is not found in the empty JSON string", ReplayEventData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ReplayEventData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ReplayEventData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ReplayEventData.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("original_event_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `original_event_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("original_event_id").toString()));
      }
      if (!jsonObj.get("replay_event_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `replay_event_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("replay_event_id").toString()));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReplayEventData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReplayEventData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReplayEventData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReplayEventData.class));

       return (TypeAdapter<T>) new TypeAdapter<ReplayEventData>() {
           @Override
           public void write(JsonWriter out, ReplayEventData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ReplayEventData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ReplayEventData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ReplayEventData
   * @throws IOException if the JSON string is invalid with respect to ReplayEventData
   */
  public static ReplayEventData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReplayEventData.class);
  }

  /**
   * Convert an instance of ReplayEventData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

