/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.gethook.model.AggregateTotals;
import dev.gethook.model.StatsDailyItem;
import dev.gethook.model.StatsStatusItem;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dev.gethook.JSON;

/**
 * StatsData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-30T12:12:30.561561807Z[Etc/UTC]", comments = "Generator version: 7.20.0")
public class StatsData {
  public static final String SERIALIZED_NAME_BY_STATUS = "by_status";
  @SerializedName(SERIALIZED_NAME_BY_STATUS)
  @javax.annotation.Nonnull
  private List<StatsStatusItem> byStatus = new ArrayList<>();

  public static final String SERIALIZED_NAME_DAILY = "daily";
  @SerializedName(SERIALIZED_NAME_DAILY)
  @javax.annotation.Nonnull
  private List<StatsDailyItem> daily = new ArrayList<>();

  public static final String SERIALIZED_NAME_TOTALS = "totals";
  @SerializedName(SERIALIZED_NAME_TOTALS)
  @javax.annotation.Nonnull
  private AggregateTotals totals;

  public StatsData() {
  }

  public StatsData byStatus(@javax.annotation.Nonnull List<StatsStatusItem> byStatus) {
    this.byStatus = byStatus;
    return this;
  }

  public StatsData addByStatusItem(StatsStatusItem byStatusItem) {
    if (this.byStatus == null) {
      this.byStatus = new ArrayList<>();
    }
    this.byStatus.add(byStatusItem);
    return this;
  }

  /**
   * Get byStatus
   * @return byStatus
   */
  @javax.annotation.Nonnull
  public List<StatsStatusItem> getByStatus() {
    return byStatus;
  }

  public void setByStatus(@javax.annotation.Nonnull List<StatsStatusItem> byStatus) {
    this.byStatus = byStatus;
  }


  public StatsData daily(@javax.annotation.Nonnull List<StatsDailyItem> daily) {
    this.daily = daily;
    return this;
  }

  public StatsData addDailyItem(StatsDailyItem dailyItem) {
    if (this.daily == null) {
      this.daily = new ArrayList<>();
    }
    this.daily.add(dailyItem);
    return this;
  }

  /**
   * Get daily
   * @return daily
   */
  @javax.annotation.Nonnull
  public List<StatsDailyItem> getDaily() {
    return daily;
  }

  public void setDaily(@javax.annotation.Nonnull List<StatsDailyItem> daily) {
    this.daily = daily;
  }


  public StatsData totals(@javax.annotation.Nonnull AggregateTotals totals) {
    this.totals = totals;
    return this;
  }

  /**
   * Get totals
   * @return totals
   */
  @javax.annotation.Nonnull
  public AggregateTotals getTotals() {
    return totals;
  }

  public void setTotals(@javax.annotation.Nonnull AggregateTotals totals) {
    this.totals = totals;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatsData statsData = (StatsData) o;
    return Objects.equals(this.byStatus, statsData.byStatus) &&
        Objects.equals(this.daily, statsData.daily) &&
        Objects.equals(this.totals, statsData.totals);
  }

  @Override
  public int hashCode() {
    return Objects.hash(byStatus, daily, totals);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatsData {\n");
    sb.append("    byStatus: ").append(toIndentedString(byStatus)).append("\n");
    sb.append("    daily: ").append(toIndentedString(daily)).append("\n");
    sb.append("    totals: ").append(toIndentedString(totals)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("by_status", "daily", "totals"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("by_status", "daily", "totals"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StatsData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StatsData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in StatsData is not found in the empty JSON string", StatsData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!StatsData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `StatsData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : StatsData.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("by_status") != null) {
        if (!jsonObj.get("by_status").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `by_status` to be an array in the JSON string but got `%s`", jsonObj.get("by_status").toString()));
        }
        JsonArray jsonArraybyStatus = jsonObj.getAsJsonArray("by_status");
        // validate the required field `by_status` (array)
        for (int i = 0; i < jsonArraybyStatus.size(); i++) {
          StatsStatusItem.validateJsonElement(jsonArraybyStatus.get(i));
        }
      }
      if (jsonObj.get("daily") != null) {
        if (!jsonObj.get("daily").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `daily` to be an array in the JSON string but got `%s`", jsonObj.get("daily").toString()));
        }
        JsonArray jsonArraydaily = jsonObj.getAsJsonArray("daily");
        // validate the required field `daily` (array)
        for (int i = 0; i < jsonArraydaily.size(); i++) {
          StatsDailyItem.validateJsonElement(jsonArraydaily.get(i));
        }
      }
      // validate the required field `totals`
      AggregateTotals.validateJsonElement(jsonObj.get("totals"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StatsData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StatsData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StatsData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StatsData.class));

       return (TypeAdapter<T>) new TypeAdapter<StatsData>() {
           @Override
           public void write(JsonWriter out, StatsData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StatsData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StatsData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StatsData
   * @throws IOException if the JSON string is invalid with respect to StatsData
   */
  public static StatsData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StatsData.class);
  }

  /**
   * Convert an instance of StatsData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

