/*
 * GetHook API
 * Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.gethook.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import dev.gethook.JSON;

/**
 * StatsDailyItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-25T21:12:20.197395346Z[Etc/UTC]", comments = "Generator version: 7.20.0")
public class StatsDailyItem {
  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  @javax.annotation.Nonnull
  private String date;

  public static final String SERIALIZED_NAME_DELIVERED = "delivered";
  @SerializedName(SERIALIZED_NAME_DELIVERED)
  @javax.annotation.Nonnull
  private Integer delivered;

  public static final String SERIALIZED_NAME_FAILED = "failed";
  @SerializedName(SERIALIZED_NAME_FAILED)
  @javax.annotation.Nonnull
  private Integer failed;

  public static final String SERIALIZED_NAME_INBOUND = "inbound";
  @SerializedName(SERIALIZED_NAME_INBOUND)
  @javax.annotation.Nonnull
  private Integer inbound;

  public static final String SERIALIZED_NAME_OUTBOUND = "outbound";
  @SerializedName(SERIALIZED_NAME_OUTBOUND)
  @javax.annotation.Nonnull
  private Integer outbound;

  public StatsDailyItem() {
  }

  public StatsDailyItem date(@javax.annotation.Nonnull String date) {
    this.date = date;
    return this;
  }

  /**
   * Get date
   * @return date
   */
  @javax.annotation.Nonnull
  public String getDate() {
    return date;
  }

  public void setDate(@javax.annotation.Nonnull String date) {
    this.date = date;
  }


  public StatsDailyItem delivered(@javax.annotation.Nonnull Integer delivered) {
    this.delivered = delivered;
    return this;
  }

  /**
   * Get delivered
   * @return delivered
   */
  @javax.annotation.Nonnull
  public Integer getDelivered() {
    return delivered;
  }

  public void setDelivered(@javax.annotation.Nonnull Integer delivered) {
    this.delivered = delivered;
  }


  public StatsDailyItem failed(@javax.annotation.Nonnull Integer failed) {
    this.failed = failed;
    return this;
  }

  /**
   * Get failed
   * @return failed
   */
  @javax.annotation.Nonnull
  public Integer getFailed() {
    return failed;
  }

  public void setFailed(@javax.annotation.Nonnull Integer failed) {
    this.failed = failed;
  }


  public StatsDailyItem inbound(@javax.annotation.Nonnull Integer inbound) {
    this.inbound = inbound;
    return this;
  }

  /**
   * Get inbound
   * @return inbound
   */
  @javax.annotation.Nonnull
  public Integer getInbound() {
    return inbound;
  }

  public void setInbound(@javax.annotation.Nonnull Integer inbound) {
    this.inbound = inbound;
  }


  public StatsDailyItem outbound(@javax.annotation.Nonnull Integer outbound) {
    this.outbound = outbound;
    return this;
  }

  /**
   * Get outbound
   * @return outbound
   */
  @javax.annotation.Nonnull
  public Integer getOutbound() {
    return outbound;
  }

  public void setOutbound(@javax.annotation.Nonnull Integer outbound) {
    this.outbound = outbound;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatsDailyItem statsDailyItem = (StatsDailyItem) o;
    return Objects.equals(this.date, statsDailyItem.date) &&
        Objects.equals(this.delivered, statsDailyItem.delivered) &&
        Objects.equals(this.failed, statsDailyItem.failed) &&
        Objects.equals(this.inbound, statsDailyItem.inbound) &&
        Objects.equals(this.outbound, statsDailyItem.outbound);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, delivered, failed, inbound, outbound);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatsDailyItem {\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    delivered: ").append(toIndentedString(delivered)).append("\n");
    sb.append("    failed: ").append(toIndentedString(failed)).append("\n");
    sb.append("    inbound: ").append(toIndentedString(inbound)).append("\n");
    sb.append("    outbound: ").append(toIndentedString(outbound)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("date", "delivered", "failed", "inbound", "outbound"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("date", "delivered", "failed", "inbound", "outbound"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StatsDailyItem
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StatsDailyItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in StatsDailyItem is not found in the empty JSON string", StatsDailyItem.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!StatsDailyItem.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `StatsDailyItem` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : StatsDailyItem.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("date").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `date` to be a primitive type in the JSON string but got `%s`", jsonObj.get("date").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StatsDailyItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StatsDailyItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StatsDailyItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StatsDailyItem.class));

       return (TypeAdapter<T>) new TypeAdapter<StatsDailyItem>() {
           @Override
           public void write(JsonWriter out, StatsDailyItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StatsDailyItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StatsDailyItem given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StatsDailyItem
   * @throws IOException if the JSON string is invalid with respect to StatsDailyItem
   */
  public static StatsDailyItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StatsDailyItem.class);
  }

  /**
   * Convert an instance of StatsDailyItem to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

